marvel_inventory/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from marvel_inventory.forms import UserLoginForm
from marvel_inventory.models import User, db, check_password_hash
from flask_login import login_user, logout_user, current_user, login_required

auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    form = UserLoginForm()

    if request.method == 'POST' and form.validate_on_submit():
        try:
            first_name = form.first_name.data
            last_name = form.last_name.data
            username = form.username.data
            date_created = form.date_created.data
            email = form.email.data
            password = form.password.data
            print(email, username)

            user = User(first_name=first_name, last_name=last_name, date_created=date_created, email=email,
                        password=password, username=username)
            db.session.add(user)
            db.session.commit()

            flash(f'You have successfully created a user account {username}', 'user-created')

            # Check if the flash message is present
            print(flash('user-created'))

            return redirect(url_for('auth.signin'))
        except Exception as e:
            # Print the exception message for debugging
            print(f"Exception: {str(e)}")
            flash('An error occurred while creating the user account', 'error')

    return render_template('signup.html', form=form)


@auth.route('/signin', methods=['GET', 'POST'])
def signin():
    form = UserLoginForm()

    if request.method == 'POST' and not form.validate_on_submit():
        print(form.errors)
        try:
            email = form.email.data
            password = form.password.data
            print(email, password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                print(f"This is the logged user: {logged_user}")
                login_user(logged_user)
                flash('You were successfully logged in: Via Email/Password', 'auth-success')
                return redirect(url_for('site.profile'))
            else:
                flash('Your Email/Password is incorrect', 'auth-failed')
                return redirect(url_for('auth.signin'))
        except Exception as e:
            # Print the exception message for debugging
            print(f"Exception: {str(e)}")
            flash('An error occurred while signing in', 'error')

    return render_template('signin.html', form=form)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

marvel_inventory/site/routes.py
from flask import Blueprint, render_template, redirect, request,url_for, flash
from flask_login import login_required, current_user
from marvel_inventory.forms import MarvelCharacterInfo
from marvel_inventory.models import Character, db



"""
    Note that in the below code,
    some arguments are specified when creating Blueprint objects.
    The first argument, 'site' is the Blueprint's name,
    which flask uses for routing.
    The second argument, __name__,  is the Blueprint's import name, 
    which flask uses to locate the Blueprint's resources
"""

site = Blueprint('site', __name__, template_folder = 'site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile', methods = ['GET', 'POST'])
@login_required
def profile():
    marvel_character = MarvelCharacterInfo()

    try:
        if request.method == "POST" and marvel_character.validate_on_submit():
            name = marvel_character.name.data
            description = marvel_character.description.data
            comics_appeared_in = marvel_character.comics_appeared_in.data
            super_power = marvel_character.super_power.data
            user_token = current_user.token

            character = Character(name, description, comics_appeared_in, super_power, user_token)

            db.session.add(character)
            db.session.commit()

            return redirect(url_for('site.profile'))
    except:
        raise Exception("An error occurred while creating Character try again!")

    current_user_token = current_user.token

    characters = Character.query.filter_by(user_token=current_user_token).all()

    return render_template('profile.html', form=marvel_character, characters=characters)

marvel_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Marvel Inventory Api</title>
</head>
<body>

<!-- Nav Bar Below -->
<nav class="ct-nav">
    <div>
        <img src="../static/images/logo.png" alt="Car Red">
    </div>
    <div>
        <ul id="horizontal-list">
            <a href="{{ url_for('site.home') }}">
                <li>The Marvel Inventory API</li>
            </a>
            <a href="">
                <li>View</li>
            </a>
            <a href="{{ url_for('site.profile') }}">
                <li>Profile</li>
            </a>
            <a href="{{ url_for('auth.logout') }}">
                <li>Log Out</li>
            </a>
            <a href="{{ url_for('auth.signin') }}">
                <li>Sign In</li>
            </a>
            <a href="{{ url_for('auth.signup') }}">
                <li>Sign Up</li>
            </a>
        </ul>
    </div>
</nav>

{% block content %}
{% endblock content %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

marvel_inventory/templates/marvel_character_form.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group"><br />
      <fieldset id="name-field">
        {{ form.name(class="form-control", placeholder="Name") }}
      </fieldset><br />
      <fieldset id="description-field">
        {{ form.description(class="form-control", placeholder="Description") }}
      </fieldset><br />
      <fieldset id="comics_appeared_in-field">
        {{ form.comics_appeared_in(class="form-control", placeholder="Comics Appeared In") }}
      </fieldset><br />
      <fieldset id="super_power-field">
        {{ form.super_power(class="form-control", placeholder="Super Power") }}
      </fieldset><br />
      <br /><br />
      <!-- Submit Button Area -->
      {{ form.submit_button(class="btn btn-primary btn-block mt-2") }}
    </div>   
  </form>
  

marvel_inventory/templates/signin.html
<!--HTML Produced By The Flask Form-->
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <!-- <fieldset id="username-field">
            {{ form.username.label }}
            {{ form.username(class = "form-control", placeholder = "Type Username Here...")}}
        </fieldset> -->
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "Place Email Here...")}}
        </fieldset>

        <fieldset id="password-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Place Password Here...")}}
        </fieldset>

        <!--Submit Button Area-->
        {{ form.submit_button(class = "btn btn-primary btn-block") }}
    </div>
</form>

marvel_inventory/templates/signup.html
<!--HTML Produced By The Flask Form-->
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="first_name-field">
            {{ form.first_name.label }}
            {{ form.first_name(class = "form-control", placeholder = "Type First Name Here.")}}
        </fieldset>
        <fieldset id="last_name-field">
            {{ form.last_name.label }}
            {{ form.last_name(class = "form-control", placeholder = "Type Last Name Here...")}}
        </fieldset>
        <fieldset id="username-field">
            {{ form.username.label }}
            {{ form.username(class = "form-control", placeholder = "Type Username Here...")}}
        </fieldset>
        <fieldset id="date_created-field">
            {{ form.date_created.label }}
            {{ form.date_created(class = "form-control", placeholder = "Insert Date Created Here...")}}
        </fieldset>
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "Place Email Here...")}}
        </fieldset>

        <fieldset id="password-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Place Password Here...")}}
        </fieldset>

        <!--Submit Button Area-->
        {{ form.submit_button(class = "btn btn-primary btn-block") }}
    </div>
</form>